const ROUTES={
  5:{label:'5天4晚',subtitle:'从茶园到侗寨，完整走进五天村寨生活',priceText:'¥4936起',days:[['Day 1','开营仪式 · 采茶 · 茶禾定制家宴 · 窝囊漂 · 接风宴与篝火晚会'],['Day 2','抓禾花鱼 · 制茶 · 砍柴火 · 喊更 · 给老人做饭'],['Day 3','布央仙人山看日出 · 茶禾休整 · 程阳榫卯搭建 · 冠洞百家宴'],['Day 4','侗家人日行一善 · 巡山识百草 · 烧烤篝火'],['Day 5','砍竹制作竹工艺品 · 竹筒奶茶 · 家宴 · 复盘回程']]},
  3:{label:'3天2晚',subtitle:'三天完成自然、非遗、家宴与村寨共益体验',priceText:'¥3260起',days:[['Day 1','开营；抓禾花鱼/抓泥鳅/竹筒奶茶3选1；家宴；窝囊漂/喊山巡山/采茶3选1；接风宴篝火/喊更给老人做饭2选1'],['Day 2','仙人山日出/侗寨染布/采茶制茶三项中2选1；家宴；程阳榫卯/侗笛2选1；冠洞火塘宴'],['Day 3','日行一善/竹杯奶茶/制茶三项中2选1；家宴；复盘返程']]},
  2:{label:'2天1晚',subtitle:'一个周末，也能认真体验一次村寨生活',priceText:'¥2306起',days:[['Day 1','开营；抓禾花鱼/抓泥鳅/竹筒奶茶3选1；家宴；窝囊漂/喊山巡山/采茶3选1；接风宴篝火/喊更给老人做饭2选1'],['Day 2','日行一善/竹杯奶茶/制茶三项中2选1；家宴；复盘返程']]}
};
const ROUTE_PRICES={5:[[2,4936],[3,6609],[4,8264],[5,9880]],3:[[2,3260],[3,4695],[4,6112],[5,7490]],2:[[2,2306],[3,3414],[4,4404],[5,5355]]};
function getRouteDays(){const value=parseInt(new URLSearchParams(location.search).get('days')||'5',10);return [5,3,2].includes(value)?value:5}
const FULL_SCHEDULE={5:[
{title:'初见马胖村',hint:'开营、茶园与接风',items:[['08:30-09:00','开营仪式','认识带队人与村寨'],['09:00-11:30','采茶','跟随茶农走进茶园'],['12:00-14:30','茶禾定制家宴 + 午休',''],['14:30-15:00','茶禾下午茶',''],['15:00-17:00','窝囊漂','山水间轻松漂流'],['17:30-20:30','拦路接风宴 + 篝火晚会','']]},
{title:'跟村民过一天',hint:'抓鱼、制茶与共餐',items:[['08:30-09:00','早餐',''],['09:00-10:30','抓禾花鱼',''],['10:30-11:30','制茶',''],['12:00-14:30','茶禾定制家宴 + 午休',''],['14:30-15:00','茶禾下午茶',''],['15:00-17:00','砍柴火','准备晚餐所需柴火'],['17:00-17:30','喊更',''],['17:30-20:30','给老人做饭','与老人欢聚，品尝自己做的饭菜']]},
{title:'走进侗寨非遗',hint:'日出、榫卯与百家宴',items:[['05:30-08:00','布央仙人山日出',''],['08:00-11:30','茶禾休整','早餐与自由活动'],['12:00-14:30','茶禾定制家宴 + 午休',''],['14:30-15:00','茶禾下午茶',''],['15:00-17:00','程阳榫卯搭建','认识侗族木构智慧'],['17:30-20:30','冠洞芦笙百家宴','']]},
{title:'把善意留在村里',hint:'共益、草木与山野夜晚',items:[['08:30-09:00','早餐',''],['09:00-11:30','侗家人日行一善','参与村寨共益行动'],['12:00-14:30','茶禾定制家宴 + 午休',''],['14:30-15:00','茶禾下午茶',''],['15:00-17:00','巡山识百草','跟随村民认识山野植物'],['17:30-20:30','烧烤 + 篝火晚会','']]},
{title:'带着作品回家',hint:'竹艺、奶茶与复盘',items:[['08:30-09:00','早餐',''],['09:00-11:30','砍竹制作竹工艺品 + 竹筒奶茶','完成自己的竹制作品'],['12:00-14:30','茶禾定制家宴 + 午休',''],['14:30-16:00','旅程复盘','分享收获与告别村寨'],['16:00后','前往高铁站','根据返程车次安排送站']]}
],3:[
{title:'初见马胖村',hint:'自然、家宴与村寨夜晚',items:[['08:30-09:00','开营仪式',''],['09:00-11:30','上午体验 · 3选1','抓禾花鱼 / 抓泥鳅 / 砍竹做竹筒奶茶'],['12:00-14:30','茶禾定制家宴 + 午休',''],['14:30-15:00','茶禾下午茶',''],['15:00-17:00','下午体验 · 3选1','窝囊漂 / 喊山巡山识百草 / 采茶'],['17:30-20:30','晚间体验 · 2选1','接风宴与篝火晚会 / 喊更并给老人做饭']]},
{title:'走进侗寨非遗',hint:'自然与非遗自由组合',items:[['05:30-11:30','上午体验 · 三项中2选1','仙人山日出 / 侗寨染布 / 采茶（次日制茶）'],['12:00-14:30','茶禾定制家宴 + 午休',''],['14:30-15:00','茶禾下午茶',''],['15:00-17:00','非遗课堂 · 2选1','程阳榫卯搭建 / 侗笛学习'],['17:30-20:30','冠洞火塘宴','']]},
{title:'把一份善意留在村里',hint:'共益、手作与返程',items:[['08:30-09:00','早餐',''],['09:00-11:30','上午体验 · 三项中2选1','日行一善 / 竹杯奶茶 / 制茶'],['12:00-14:30','茶禾定制家宴 + 午休',''],['14:30-16:00','旅程复盘',''],['16:00后','前往高铁站','根据返程车次安排送站']]}
],2:[
{title:'初见马胖村',hint:'自然、家宴与村寨夜晚',items:[['08:30-09:00','开营仪式',''],['09:00-11:30','上午体验 · 3选1','抓禾花鱼 / 抓泥鳅 / 砍竹做竹筒奶茶'],['12:00-14:30','茶禾定制家宴 + 午休',''],['14:30-15:00','茶禾下午茶',''],['15:00-17:00','下午体验 · 3选1','窝囊漂 / 喊山巡山识百草 / 采茶'],['17:30-20:30','晚间体验 · 2选1','接风宴与篝火晚会 / 喊更并给老人做饭']]},
{title:'把一份善意留在村里',hint:'共益、手作与返程',items:[['08:30-09:00','早餐',''],['09:00-11:30','上午体验 · 三项中2选1','日行一善 / 竹杯奶茶 / 制茶'],['12:00-14:30','茶禾定制家宴 + 午休',''],['14:30-16:00','旅程复盘',''],['16:00后','前往高铁站','根据返程车次安排送站']]}
]};
function routePlanHTML(days,compact=false){return days.map(([d,text])=>`<div class="route-day ${compact?'compact':''}"><b>${d}</b><p>${text}</p></div>`).join('')}
function routeVideoHTML(n){return `<div class="route-video"><span>${ROUTES[n].label}线路视频</span><button aria-label="播放${ROUTES[n].label}线路视频">▶</button><small>人物 · 村寨 · 每日体验</small></div>`}
function initHomeRoutes(){const box=document.getElementById('homeRoutePlan');function show(n){const r=ROUTES[n];box.innerHTML=`${routeVideoHTML(n)}<div class="route-summary"><h3>${r.subtitle}</h3><span>${r.priceText}</span></div>${routePlanHTML(r.days,true)}<a class="route-more" href="route-custom.html?days=${n}">查看完整行程</a>`;box.querySelector('.route-video button').onclick=()=>box.querySelector('.route-video').classList.toggle('playing')}document.querySelectorAll('.route-tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.route-tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');show(t.dataset.days)});show(5)}
function initRouteHub(){const plan=document.getElementById('routePlan'),packages=document.getElementById('packageList'),open=document.getElementById('openBooking');let current=5,people=2,price=0;function show(n){current=Number(n);const r=ROUTES[current],prices=ROUTE_PRICES[current];document.getElementById('routeSubtitle').textContent=r.subtitle;plan.innerHTML=routeVideoHTML(current)+routePlanHTML(r.days);plan.querySelector('.route-video button').onclick=()=>plan.querySelector('.route-video').classList.toggle('playing');packages.innerHTML=prices.length?prices.map(([p,v],i)=>`<button class="package ${i===0?'active':''}" data-people="${p}" data-price="${v}"><span><b>${p}人同行</b><small>整组定制出行</small></span><strong>¥${v}</strong></button>`).join(''):'<div class="notice">5天4晚价格需根据出行日期、住宿房型和人数确认，提交后由顾问报价。</div>';people=prices[0]?.[0]||0;price=prices[0]?.[1]||0;open.textContent=prices.length?`选择${people}人 · ¥${price}`:'咨询5天4晚报价';packages.querySelectorAll('.package').forEach(x=>x.onclick=()=>{packages.querySelectorAll('.package').forEach(y=>y.classList.remove('active'));x.classList.add('active');people=x.dataset.people;price=x.dataset.price;open.textContent=`选择${people}人 · ¥${price}`});document.querySelectorAll('#fullRoute,#fullRouteBottom').forEach(x=>x.href=`route-custom.html?days=${current}`)}document.querySelectorAll('.route-tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.route-tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');show(t.dataset.days)});open.onclick=()=>{document.getElementById('modalRoute').textContent=ROUTES[current].label;document.getElementById('modalPeople').textContent=people?people+'人':'待确认';document.getElementById('modalPrice').textContent=price?'¥'+price:'顾问报价';document.getElementById('bookingModal').classList.add('show')};show(5)}
function choiceLimit(name){if(/中2选1/.test(name))return 2;return /[23]选1/.test(name)?1:0}
function fullTimelineHTML(days){return days.map((day,i)=>`<article class="day-card"><header><span>D${i+1}</span><div><h3>${day.title}</h3><p>${day.hint}</p></div></header><div class="day-timeline">${day.items.map(([time,name,note],j)=>{const limit=choiceLimit(name),options=limit&&note?note.split('/').map(x=>x.trim()):[];return `<div class="time-stop ${limit?'has-choice':''}"><time>${time}</time><div><b>${name}</b>${options.length?`<div class="route-choice" data-limit="${limit}" data-key="d${i}i${j}"><small>请选择 ${limit} 项</small>${options.map(x=>`<button type="button"><i>○</i>${x}</button>`).join('')}<em>已选 0/${limit}</em></div>`:(note?`<p>${note}</p>`:'')}</div></div>`}).join('')}</div></article>`).join('')}
function bindRouteChoices(){document.querySelectorAll('.route-choice').forEach(group=>{const limit=Number(group.dataset.limit),buttons=[...group.querySelectorAll('button')],counter=group.querySelector('em');buttons.forEach(btn=>btn.onclick=()=>{const selected=buttons.filter(x=>x.classList.contains('selected'));if(btn.classList.contains('selected'))btn.classList.remove('selected');else if(selected.length<limit)btn.classList.add('selected');else{const toast=document.getElementById('toast');toast.textContent=`此处最多选择${limit}项`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1500)}buttons.forEach(x=>x.querySelector('i').textContent=x.classList.contains('selected')?'●':'○');counter.textContent=`已选 ${buttons.filter(x=>x.classList.contains('selected')).length}/${limit}`})})}
function renderFullRoute(){const n=getRouteDays(),r=ROUTES[n];document.getElementById('routeTitle').textContent=r.label+'完整行程';document.getElementById('routeIntro').textContent=r.subtitle;document.getElementById('fullDays').innerHTML=fullTimelineHTML(FULL_SCHEDULE[n]);bindRouteChoices()}
function initFullBooking(){const n=getRouteDays(),modal=document.getElementById('fullBookingModal'),list=document.getElementById('fullPackageList'),confirm=document.getElementById('confirmPackage'),prices=ROUTE_PRICES[n].length?ROUTE_PRICES[n]:[[2,null],[3,null],[4,null],[5,null]];let selected=prices[0];document.getElementById('packageSheetDesc').textContent=prices[0][1]?'选择同行人数，价格为整组套餐总价':'5天4晚根据日期、住宿房型与人数由顾问报价';function draw(){list.innerHTML=prices.map(([people,price])=>`<button class="package ${people===selected[0]?'active':''}" data-people="${people}"><span><b>${people}人同行</b><small>整组定制出行</small></span><strong>${price?'¥'+price:'顾问报价'}</strong></button>`).join('');list.querySelectorAll('.package').forEach(btn=>btn.onclick=()=>{selected=prices.find(x=>x[0]===Number(btn.dataset.people));draw()});confirm.textContent=selected[1]?`确定 · ${selected[0]}人 ¥${selected[1]}`:`确定 · ${selected[0]}人 顾问报价`}document.getElementById('routeBookLink').onclick=()=>modal.classList.add('show');document.getElementById('closeFullBooking').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};confirm.onclick=()=>{modal.classList.remove('show');const toast=document.getElementById('toast');toast.textContent=`已选择${selected[0]}人${selected[1]?'套餐 ¥'+selected[1]:'，顾问报价'}`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)};draw()}
